/**
 * VOOM Ghana — Products Seed Script
 * Run: npx tsx server/seed-products.ts
 *
 * Seeds 240 realistic listings across 12 categories for 2 demo vendors
 * Prices in GHS based on Ghana market data (Tonaton, Jiji, Abossey Okai).
 */

import { getDb } from "./db";
import { products } from "../drizzle/schema";

const TONATON = 3; // Tonaton Auto Parts
const JIJI    = 4; // Jiji Spare Parts Hub

type Condition = "new" | "used" | "refurbished";

interface Product {
  vendorId: number;
  categoryId: number;
  name: string;
  description: string;
  price: string;
  brand: string;
  condition: Condition;
  vehicleMake: string;
  vehicleModel: string;
  yearFrom: number;
  yearTo: number;
  sku: string;
  oemPartNumber?: string;
  quantity: number;
  featured?: boolean;
}

// ─── CAT 1: Engine & Drivetrain ──────────────────────────────────────────────

const cat1_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 1, name: "Toyota Corolla Timing Belt Kit", description: "OEM-quality timing belt kit with tensioner and water pump. Fits 2003-2015 Corolla 1.6L & 1.8L. Prevents costly engine damage.", price: "380.00", brand: "Gates", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2015, sku: "TN-ENG-001", oemPartNumber: "13568-09070", quantity: 25, featured: true },
  { vendorId: TONATON, categoryId: 1, name: "Honda Civic Spark Plugs (Set of 4)", description: "Iridium spark plugs for Honda Civic 1.8L. Extended 80,000km service life. Improved cold starts and fuel efficiency.", price: "145.00", brand: "NGK", condition: "new", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2006, yearTo: 2015, sku: "TN-ENG-002", oemPartNumber: "NGK-IZFR6K11", quantity: 50 },
  { vendorId: TONATON, categoryId: 1, name: "Toyota RAV4 Engine Mount (Front)", description: "Heavy-duty engine mount reduces vibration and noise. Direct OEM replacement for RAV4 2.0L & 2.5L models. Easy bolt-on fit.", price: "320.00", brand: "Febest", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2006, yearTo: 2018, sku: "TN-ENG-003", oemPartNumber: "12305-0H080", quantity: 15 },
  { vendorId: TONATON, categoryId: 1, name: "Hyundai Tucson Ignition Coil", description: "Direct-fit ignition coil for Hyundai Tucson 2.0L & 2.4L. Restores power and eliminates misfires. Pack of 1.", price: "210.00", brand: "Bosch", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2010, yearTo: 2020, sku: "TN-ENG-004", oemPartNumber: "27301-2B010", quantity: 30 },
  { vendorId: TONATON, categoryId: 1, name: "Nissan X-Trail Fuel Injector", description: "OEM-spec fuel injector for Nissan X-Trail 2.0L petrol. Precision spray pattern for optimal combustion and emissions.", price: "495.00", brand: "Denso", condition: "new", vehicleMake: "Nissan", vehicleModel: "X-Trail", yearFrom: 2007, yearTo: 2017, sku: "TN-ENG-005", oemPartNumber: "16600-JD70A", quantity: 18 },
  { vendorId: TONATON, categoryId: 1, name: "Toyota Camry Alternator 90A", description: "Remanufactured alternator for Toyota Camry 2.4L & 3.5L. Tested to OEM specs. Core deposit not required.", price: "680.00", brand: "Denso", condition: "refurbished", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2017, sku: "TN-ENG-006", oemPartNumber: "27060-28290", quantity: 8 },
  { vendorId: TONATON, categoryId: 1, name: "Honda Accord Starter Motor", description: "Brand new starter motor for Honda Accord 2.0L & 2.4L. 12-month warranty. Bolt-on replacement, no modifications needed.", price: "560.00", brand: "Bosch", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2015, sku: "TN-ENG-007", oemPartNumber: "31200-RBJ-005", quantity: 12 },
  { vendorId: TONATON, categoryId: 1, name: "Toyota Hilux Fuel Pump Assembly", description: "In-tank fuel pump with float sender unit. Fits Hilux 2.7L petrol. Genuine quality, direct-fit OEM replacement.", price: "750.00", brand: "Walbro", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "TN-ENG-008", oemPartNumber: "77020-0K030", quantity: 10 },
  { vendorId: TONATON, categoryId: 1, name: "Hyundai Elantra Valve Cover Gasket", description: "Silicone valve cover gasket for Elantra 1.6L & 2.0L. Eliminates oil leaks. Includes spark plug tube seals.", price: "120.00", brand: "Victor Reinz", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Elantra", yearFrom: 2011, yearTo: 2020, sku: "TN-ENG-009", oemPartNumber: "22441-2B000", quantity: 40 },
  { vendorId: TONATON, categoryId: 1, name: "Kia Sportage Throttle Body", description: "Electronic throttle body for Kia Sportage 2.0L GDI. Improves throttle response. Includes gasket. Plug-and-play.", price: "880.00", brand: "Bosch", condition: "new", vehicleMake: "Kia", vehicleModel: "Sportage", yearFrom: 2011, yearTo: 2020, sku: "TN-ENG-010", oemPartNumber: "35100-2G300", quantity: 6 },
];

const cat1_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 1, name: "Toyota Corolla Engine Block 1ZZ", description: "Used engine block for Corolla 1.8L 1ZZ-FE engine. Tested and compression-checked. Good for rebuild or swap.", price: "2800.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2008, sku: "JJ-ENG-001", quantity: 2 },
  { vendorId: JIJI, categoryId: 1, name: "Honda CR-V Timing Chain Kit", description: "Complete timing chain kit for CR-V 2.4L K24 engine. Includes chain, guides, tensioner and VTC gears.", price: "420.00", brand: "Melling", condition: "new", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2007, yearTo: 2016, sku: "JJ-ENG-002", oemPartNumber: "14401-RAA-A01", quantity: 14 },
  { vendorId: JIJI, categoryId: 1, name: "Nissan Almera Spark Plugs (Set of 4)", description: "Copper core spark plugs for Almera 1.6L. Best value for high-mileage engines. Replace every 30,000 km.", price: "75.00", brand: "Champion", condition: "new", vehicleMake: "Nissan", vehicleModel: "Almera", yearFrom: 2000, yearTo: 2015, sku: "JJ-ENG-003", quantity: 60 },
  { vendorId: JIJI, categoryId: 1, name: "Toyota Land Cruiser Turbocharger", description: "Rebuilt turbocharger for Land Cruiser 1HD-T & 1KZ-TE diesel engines. Balanced and tested. 6-month warranty.", price: "3200.00", brand: "Garrett", condition: "refurbished", vehicleMake: "Toyota", vehicleModel: "Land Cruiser", yearFrom: 2000, yearTo: 2007, sku: "JJ-ENG-004", quantity: 3, featured: true },
  { vendorId: JIJI, categoryId: 1, name: "Hyundai Sonata Camshaft", description: "Used camshaft for Sonata 2.4L Theta II engine. Inspected, no wear marks. Ideal for engine rebuild projects.", price: "650.00", brand: "Hyundai OEM", condition: "used", vehicleMake: "Hyundai", vehicleModel: "Sonata", yearFrom: 2010, yearTo: 2015, sku: "JJ-ENG-005", quantity: 4 },
  { vendorId: JIJI, categoryId: 1, name: "Ford Ranger EGR Valve", description: "New EGR valve for Ranger 2.5L & 3.0L TDI diesel. Clears engine management light. Direct OEM fit.", price: "340.00", brand: "Pierburg", condition: "new", vehicleMake: "Ford", vehicleModel: "Ranger", yearFrom: 2006, yearTo: 2016, sku: "JJ-ENG-006", oemPartNumber: "CB-022-058", quantity: 9 },
  { vendorId: JIJI, categoryId: 1, name: "Mitsubishi Pajero Flywheel", description: "Used flywheel for Pajero 3.0L V6 & 3.5L V6 petrol. Ring gear intact, surface good for machining.", price: "480.00", brand: "Mitsubishi OEM", condition: "used", vehicleMake: "Mitsubishi", vehicleModel: "Pajero/Montero", yearFrom: 2000, yearTo: 2013, sku: "JJ-ENG-007", quantity: 3 },
  { vendorId: JIJI, categoryId: 1, name: "Toyota Hilux Crankshaft", description: "Second-hand crankshaft for Hilux 2.5L & 3.0L D-4D diesel. Micro-polished journals. Sold with bearing set.", price: "1200.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2015, sku: "JJ-ENG-008", quantity: 2 },
  { vendorId: JIJI, categoryId: 1, name: "Honda Accord Drive Belt Set", description: "Serpentine belt set for Accord 2.4L. Includes alternator, AC, and power steering belts. OEM spec dimensions.", price: "135.00", brand: "Bando", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2003, yearTo: 2012, sku: "JJ-ENG-009", quantity: 25 },
  { vendorId: JIJI, categoryId: 1, name: "Volkswagen Golf Intake Manifold", description: "Used intake manifold for Golf Mk5/Mk6 2.0L TDI. Cleaned and tested. Good condition, no cracks.", price: "520.00", brand: "VW OEM", condition: "used", vehicleMake: "Volkswagen", vehicleModel: "Golf", yearFrom: 2004, yearTo: 2013, sku: "JJ-ENG-010", quantity: 4 },
];

// ─── CAT 2: Brakes, Suspension & Steering ────────────────────────────────────

const cat2_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 2, name: "Toyota Corolla Front Brake Pads", description: "Premium ceramic front brake pads for Corolla. Low dust, low noise. Includes shims. Fits 2003-2020 models.", price: "180.00", brand: "Brembo", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2020, sku: "TN-BRK-001", oemPartNumber: "04465-12520", quantity: 45, featured: true },
  { vendorId: TONATON, categoryId: 2, name: "Honda CR-V Shock Absorber Pair (Front)", description: "Gas-pressurised front shock absorbers for CR-V. Restores ride comfort and handling. Set of 2 with mounts.", price: "680.00", brand: "KYB", condition: "new", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2007, yearTo: 2016, sku: "TN-BRK-002", oemPartNumber: "KYB-339358", quantity: 12 },
  { vendorId: TONATON, categoryId: 2, name: "Toyota RAV4 Brake Disc Rotors (Pair)", description: "Vented front brake rotors for RAV4. Premium balanced design. G-coated to prevent rust. Set of 2.", price: "420.00", brand: "DBA", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2006, yearTo: 2018, sku: "TN-BRK-003", oemPartNumber: "43512-42080", quantity: 18 },
  { vendorId: TONATON, categoryId: 2, name: "Hyundai Tucson Control Arm (Lower)", description: "Front lower control arm for Tucson with ball joint pre-installed. Restores alignment geometry. Left or right side.", price: "390.00", brand: "Moog", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2010, yearTo: 2020, sku: "TN-BRK-004", quantity: 15 },
  { vendorId: TONATON, categoryId: 2, name: "Toyota Camry Power Steering Rack", description: "Remanufactured power steering rack for Camry 2.4L & 2.5L. Tested to OEM pressure specs. Includes inner tie rods.", price: "1350.00", brand: "ACDelco", condition: "refurbished", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2017, sku: "TN-BRK-005", oemPartNumber: "44200-06280", quantity: 5 },
  { vendorId: TONATON, categoryId: 2, name: "Nissan X-Trail Wheel Bearing Hub Assembly", description: "Front hub bearing assembly for X-Trail. Eliminates wheel noise and vibration. Includes ABS sensor ring.", price: "350.00", brand: "Timken", condition: "new", vehicleMake: "Nissan", vehicleModel: "X-Trail", yearFrom: 2007, yearTo: 2017, sku: "TN-BRK-006", oemPartNumber: "40202-JG00A", quantity: 20 },
  { vendorId: TONATON, categoryId: 2, name: "Honda Accord Rear Brake Pads & Rotors Kit", description: "Complete rear brake service kit for Accord. Includes pads, rotors, and hardware. Stops on a dime.", price: "520.00", brand: "Akebono", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2017, sku: "TN-BRK-007", quantity: 14 },
  { vendorId: TONATON, categoryId: 2, name: "Toyota Hilux CV Axle (Front Left)", description: "New front left CV axle driveshaft for Hilux 4x4. Heat-treated joints, triple-lip seals. Grease packed.", price: "780.00", brand: "GSP", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "TN-BRK-008", oemPartNumber: "43420-0K050", quantity: 8 },
  { vendorId: TONATON, categoryId: 2, name: "Kia Sportage Tie Rod End Kit", description: "Complete tie rod set (inner + outer) for Sportage. Restores steering precision. ES-sealed for Ghana conditions.", price: "280.00", brand: "Moog", condition: "new", vehicleMake: "Kia", vehicleModel: "Sportage", yearFrom: 2010, yearTo: 2020, sku: "TN-BRK-009", quantity: 22 },
  { vendorId: TONATON, categoryId: 2, name: "Toyota Corolla Rear Coil Spring Set", description: "Heavy-duty rear coil springs for Corolla. Corrects sagging and restores ride height. Set of 2.", price: "310.00", brand: "Monroe", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2008, yearTo: 2020, sku: "TN-BRK-010", quantity: 18 },
];

const cat2_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 2, name: "Toyota Land Cruiser Prado Front Shocks", description: "Used front shock absorbers from Prado GX 2010. Good condition, less than 50k km remaining life.", price: "380.00", brand: "Rancho", condition: "used", vehicleMake: "Toyota", vehicleModel: "Land Cruiser Prado", yearFrom: 2003, yearTo: 2010, sku: "JJ-BRK-001", quantity: 2, featured: true },
  { vendorId: JIJI, categoryId: 2, name: "Honda Civic Brake Pad Set (Front)", description: "Budget-friendly semi-metallic front pads for Civic. Good heat dissipation. Safe and reliable for daily driving.", price: "110.00", brand: "Remsa", condition: "new", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2006, yearTo: 2015, sku: "JJ-BRK-002", quantity: 35 },
  { vendorId: JIJI, categoryId: 2, name: "Hyundai Santa Fe Strut Assembly (Front)", description: "Complete front strut assembly for Santa Fe. Includes spring, bearing and mount. Ready to bolt in.", price: "550.00", brand: "Sachs", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Santa Fe", yearFrom: 2007, yearTo: 2018, sku: "JJ-BRK-003", quantity: 6 },
  { vendorId: JIJI, categoryId: 2, name: "Nissan Navara Leaf Spring (Rear)", description: "Heavy-duty rear leaf spring for Navara pickup. Extra add-a-leaf for load capacity. Direct bolt-on.", price: "480.00", brand: "Dobinsons", condition: "new", vehicleMake: "Nissan", vehicleModel: "Navara", yearFrom: 2005, yearTo: 2019, sku: "JJ-BRK-004", quantity: 8 },
  { vendorId: JIJI, categoryId: 2, name: "Toyota Camry Brake Caliper (Front Right)", description: "Remanufactured right front brake caliper for Camry. Pressure-tested. Includes new bleeder screw.", price: "290.00", brand: "Cardone", condition: "refurbished", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2017, sku: "JJ-BRK-005", quantity: 10 },
  { vendorId: JIJI, categoryId: 2, name: "BMW 3 Series Bushing Kit", description: "Complete front suspension bushing kit for BMW E90/E91. Includes wishbone, anti-roll and subframe bushings.", price: "620.00", brand: "Lemforder", condition: "new", vehicleMake: "BMW", vehicleModel: "3 Series", yearFrom: 2005, yearTo: 2013, sku: "JJ-BRK-006", quantity: 7 },
  { vendorId: JIJI, categoryId: 2, name: "Toyota Corolla Ball Joint (Front Lower)", description: "Front lower ball joint for Corolla E120/E140. Greaseable for extended life. 12-month warranty.", price: "145.00", brand: "Moog", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2013, sku: "JJ-BRK-007", oemPartNumber: "43340-29125", quantity: 30 },
  { vendorId: JIJI, categoryId: 2, name: "Mercedes C-Class Brake Master Cylinder", description: "Used brake master cylinder from C200 W204. Tested, seals intact. Best for rebuild or emergency replacement.", price: "320.00", brand: "Mercedes OEM", condition: "used", vehicleMake: "Mercedes-Benz", vehicleModel: "C-Class", yearFrom: 2007, yearTo: 2014, sku: "JJ-BRK-008", quantity: 3 },
  { vendorId: JIJI, categoryId: 2, name: "Mazda CX-5 Hub Bearing Assembly (Rear)", description: "New rear wheel hub bearing for CX-5. Eliminates rumbling noise. Press-in fit. ABS ring included.", price: "310.00", brand: "Timken", condition: "new", vehicleMake: "Mazda", vehicleModel: "CX-5", yearFrom: 2013, yearTo: 2020, sku: "JJ-BRK-009", quantity: 12 },
  { vendorId: JIJI, categoryId: 2, name: "Ford Ranger Stabilizer Bar Link Kit", description: "Heavy-duty front sway bar links for Ranger T6. Eliminates knock-on-bump noise. Pair included.", price: "195.00", brand: "TRW", condition: "new", vehicleMake: "Ford", vehicleModel: "Ranger", yearFrom: 2012, yearTo: 2022, sku: "JJ-BRK-010", quantity: 20 },
];

// ─── CAT 3: Exterior & Body Parts ────────────────────────────────────────────

const cat3_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 3, name: "Toyota Corolla Front Bumper (2014-2019)", description: "Brand new front bumper for Corolla E170. Includes all clips and brackets. Primed, ready for painting.", price: "680.00", brand: "TYC", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2014, yearTo: 2019, sku: "TN-EXT-001", quantity: 8, featured: true },
  { vendorId: TONATON, categoryId: 3, name: "Toyota Hilux Door Handle (Front Left)", description: "Exterior door handle for Hilux Vigo. OEM color: Black. Direct replacement, no drilling required.", price: "185.00", brand: "Dorman", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2015, sku: "TN-EXT-002", oemPartNumber: "69210-0K010", quantity: 20 },
  { vendorId: TONATON, categoryId: 3, name: "Honda Accord Side Mirror (Right)", description: "Right power side mirror for Accord 2008-2015. With turn signal and puddle lamp. Foldable, heated.", price: "420.00", brand: "Dorman", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2015, sku: "TN-EXT-003", quantity: 10 },
  { vendorId: TONATON, categoryId: 3, name: "Hyundai Tucson Front Fender (Left)", description: "New left front fender for Tucson 2016-2021. Pre-drilled bolt holes. Primed aluminum-coated steel.", price: "540.00", brand: "Dorman", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2016, yearTo: 2021, sku: "TN-EXT-004", quantity: 6 },
  { vendorId: TONATON, categoryId: 3, name: "Toyota RAV4 Hood/Bonnet (2013-2018)", description: "Replacement hood for RAV4 XA40. Stamped steel, factory drilled. Lightweight and precise fit.", price: "1100.00", brand: "TYC", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2013, yearTo: 2018, sku: "TN-EXT-005", quantity: 4 },
  { vendorId: TONATON, categoryId: 3, name: "Nissan X-Trail Grille Assembly", description: "Front grille for X-Trail T31 with chrome surround. Snap-fit installation. Replaces broken or cracked units.", price: "295.00", brand: "Nissan OEM Style", condition: "new", vehicleMake: "Nissan", vehicleModel: "X-Trail", yearFrom: 2007, yearTo: 2014, sku: "TN-EXT-006", quantity: 12 },
  { vendorId: TONATON, categoryId: 3, name: "Toyota Corolla Windshield/Windscreen", description: "OEM-spec laminated windscreen for Corolla E150/E170. AGC glass, UV-coated. With rain sensor port.", price: "850.00", brand: "AGC", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2008, yearTo: 2019, sku: "TN-EXT-007", quantity: 7 },
  { vendorId: TONATON, categoryId: 3, name: "Honda CR-V Running Board Set", description: "Side running boards for CR-V 2012-2018. Polished aluminum with non-slip rubber pad. Pair.", price: "780.00", brand: "Dee Zee", condition: "new", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2012, yearTo: 2018, sku: "TN-EXT-008", quantity: 5 },
  { vendorId: TONATON, categoryId: 3, name: "Toyota Camry Rear Bumper (2015-2017)", description: "Replacement rear bumper for Camry XV50 facelift. Includes park sensor holes. Primed and ready to paint.", price: "720.00", brand: "TYC", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2015, yearTo: 2017, sku: "TN-EXT-009", quantity: 5 },
  { vendorId: TONATON, categoryId: 3, name: "Toyota Hilux Roof Rack (Steel)", description: "Heavy-duty steel roof rack for Hilux Double Cab. 100kg load capacity. Black powder coat. With mounting kit.", price: "950.00", brand: "Rhino Rack", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "TN-EXT-010", quantity: 6 },
];

const cat3_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 3, name: "Toyota Corolla Door (Front Right, Used)", description: "Used front right door from Corolla 2010 in white. Dent-free, original glass, lock mechanism good.", price: "450.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2008, yearTo: 2013, sku: "JJ-EXT-001", quantity: 1 },
  { vendorId: JIJI, categoryId: 3, name: "Honda Civic Front Bumper (2012-2015)", description: "Aftermarket front bumper for Civic FB. OEM-spec fitment. Primed and ready to paint. Good quality.", price: "380.00", brand: "K-Metal", condition: "new", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2012, yearTo: 2015, sku: "JJ-EXT-002", quantity: 7 },
  { vendorId: JIJI, categoryId: 3, name: "Hyundai Elantra Hood (Used)", description: "Used bonnet from Elantra MD 2012 in silver. Minor surface scratches, no dents. Good donor car part.", price: "280.00", brand: "Hyundai OEM", condition: "used", vehicleMake: "Hyundai", vehicleModel: "Elantra", yearFrom: 2011, yearTo: 2016, sku: "JJ-EXT-003", quantity: 2 },
  { vendorId: JIJI, categoryId: 3, name: "Nissan Pathfinder Tailgate", description: "Used rear tailgate for Pathfinder R51. In dark grey. Lock mechanism and window glass included.", price: "680.00", brand: "Nissan OEM", condition: "used", vehicleMake: "Nissan", vehicleModel: "Pathfinder", yearFrom: 2005, yearTo: 2012, sku: "JJ-EXT-004", quantity: 1, featured: true },
  { vendorId: JIJI, categoryId: 3, name: "Toyota Fortuner Rear Bumper", description: "New aftermarket rear bumper for Fortuner AN50/AN60. Includes step pad insert and sensor holes.", price: "640.00", brand: "OEM Style", condition: "new", vehicleMake: "Toyota", vehicleModel: "Fortuner", yearFrom: 2006, yearTo: 2015, sku: "JJ-EXT-005", quantity: 4 },
  { vendorId: JIJI, categoryId: 3, name: "BMW 5 Series Side Mirror (Left)", description: "Used left wing mirror from BMW F10 520i. Power-fold, heated, with turn signal. Black housing.", price: "480.00", brand: "BMW OEM", condition: "used", vehicleMake: "BMW", vehicleModel: "5 Series", yearFrom: 2010, yearTo: 2016, sku: "JJ-EXT-006", quantity: 1 },
  { vendorId: JIJI, categoryId: 3, name: "Toyota RAV4 Quarter Panel (Rear Left)", description: "Used rear left quarter panel from RAV4 XA30. No rust, one small repaired dent at bottom edge.", price: "520.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2006, yearTo: 2012, sku: "JJ-EXT-007", quantity: 1 },
  { vendorId: JIJI, categoryId: 3, name: "Honda Accord Grille (2013-2015)", description: "New upper front grille for Accord 2013-2015. Chrome accent finish. Direct OEM-style replacement.", price: "260.00", brand: "Bully", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2013, yearTo: 2015, sku: "JJ-EXT-008", quantity: 9 },
  { vendorId: JIJI, categoryId: 3, name: "Toyota Hilux Fender Liner Set", description: "Set of 4 fender liners for Hilux Vigo. Protect against mud and water. UV-resistant plastic.", price: "190.00", brand: "Dorman", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2015, sku: "JJ-EXT-009", quantity: 14 },
  { vendorId: JIJI, categoryId: 3, name: "Kia Sportage Spoiler (Rear)", description: "OEM-style rear spoiler for Sportage QL 2017-2021. ABS plastic, primed. Includes 3M tape and screws.", price: "320.00", brand: "ICI", condition: "new", vehicleMake: "Kia", vehicleModel: "Sportage", yearFrom: 2017, yearTo: 2021, sku: "JJ-EXT-010", quantity: 6 },
];

// ─── CAT 4: Headlights & Lighting ────────────────────────────────────────────

const cat4_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 4, name: "Toyota Corolla Headlight Assembly (Left)", description: "Complete left headlight for Corolla E170 2014-2019. Halogen projector, DRL included. Direct plug-in.", price: "580.00", brand: "TYC", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2014, yearTo: 2019, sku: "TN-LGT-001", oemPartNumber: "81150-02F50", quantity: 10, featured: true },
  { vendorId: TONATON, categoryId: 4, name: "Honda Accord LED Tail Light (Right)", description: "LED right tail light for Accord 2016-2020. Full LED design, smoked lens. Perfect OEM match.", price: "490.00", brand: "Depo", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2016, yearTo: 2020, sku: "TN-LGT-002", quantity: 8 },
  { vendorId: TONATON, categoryId: 4, name: "H4 LED Headlight Bulb Pair (Hi/Lo)", description: "60W H4 LED conversion kit. 6000K white light, 12,000 lumen total. Fits most Japanese cars. Plug-and-play.", price: "195.00", brand: "Philips Ultinon", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2020, sku: "TN-LGT-003", quantity: 60 },
  { vendorId: TONATON, categoryId: 4, name: "Toyota Hilux Fog Light Kit (Pair)", description: "Complete fog light kit for Hilux 2012-2018. Includes lights, harness, switch and bezels. Bright halogen H11.", price: "340.00", brand: "PIAA", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2012, yearTo: 2018, sku: "TN-LGT-004", quantity: 15 },
  { vendorId: TONATON, categoryId: 4, name: "Hyundai Tucson DRL LED Strip (Pair)", description: "Daytime running light strips for Tucson 2016-2020. Pure white 6000K. Plug-and-play wiring. Pair.", price: "280.00", brand: "OSRAM", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2016, yearTo: 2020, sku: "TN-LGT-005", quantity: 18 },
  { vendorId: TONATON, categoryId: 4, name: "Toyota Camry Headlight Assembly (Right)", description: "New right halogen headlight for Camry XV50 2012-2017. Includes bulbs. Complete OEM-style assembly.", price: "620.00", brand: "Depo", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2012, yearTo: 2017, sku: "TN-LGT-006", oemPartNumber: "81110-06750", quantity: 7 },
  { vendorId: TONATON, categoryId: 4, name: "Honda CR-V Turn Signal Light (Front)", description: "Front corner turn signal lamp for CR-V 2012-2016. Crystal clear lens. Includes correct bulb.", price: "145.00", brand: "TYC", condition: "new", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2012, yearTo: 2016, sku: "TN-LGT-007", quantity: 22 },
  { vendorId: TONATON, categoryId: 4, name: "50W H7 LED Bulb Pair — 6000K White", description: "H7 LED headlight bulbs, 50W each, 6000K daylight white. For low beam. Fits Kia, Hyundai, BMW, VW.", price: "175.00", brand: "Osram Night Breaker", condition: "new", vehicleMake: "Kia", vehicleModel: "Sportage", yearFrom: 2010, yearTo: 2022, sku: "TN-LGT-008", quantity: 45 },
  { vendorId: TONATON, categoryId: 4, name: "Toyota RAV4 LED Interior Light Kit", description: "Full interior LED conversion for RAV4. Includes map, dome, cargo and footwell lights. White 6000K.", price: "120.00", brand: "Philips", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2013, yearTo: 2020, sku: "TN-LGT-009", quantity: 30 },
  { vendorId: TONATON, categoryId: 4, name: "Nissan X-Trail License Plate Light LED", description: "LED license plate lights for X-Trail T31/T32. Pure white 6000K. 3-year warranty. Pair.", price: "75.00", brand: "Philips", condition: "new", vehicleMake: "Nissan", vehicleModel: "X-Trail", yearFrom: 2007, yearTo: 2022, sku: "TN-LGT-010", quantity: 40 },
];

const cat4_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 4, name: "Toyota Corolla Headlight Pair (Used)", description: "Used headlight pair from Corolla 2011 (E150). Both units working. Minor scuff on right housing.", price: "280.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2008, yearTo: 2013, sku: "JJ-LGT-001", quantity: 1 },
  { vendorId: JIJI, categoryId: 4, name: "Honda Civic Headlight (Left, Used)", description: "Left headlight from Civic FD 2009. Working perfectly. Minor rock chip on lens.", price: "190.00", brand: "Honda OEM", condition: "used", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2006, yearTo: 2011, sku: "JJ-LGT-002", quantity: 1 },
  { vendorId: JIJI, categoryId: 4, name: "H4 Halogen Bulb Pair 100W", description: "High power H4 halogen bulbs for brighter road visibility. Blue-coated 4200K. Set of 2.", price: "60.00", brand: "Ring", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2016, sku: "JJ-LGT-003", quantity: 80 },
  { vendorId: JIJI, categoryId: 4, name: "Mercedes E-Class Tail Light (Right)", description: "Used right tail light from W212 E300 2012. LED bar fully functional. Good condition.", price: "350.00", brand: "Mercedes OEM", condition: "used", vehicleMake: "Mercedes-Benz", vehicleModel: "E-Class", yearFrom: 2009, yearTo: 2016, sku: "JJ-LGT-004", quantity: 1, featured: true },
  { vendorId: JIJI, categoryId: 4, name: "Universal 18W LED Light Bar", description: "10-inch 18W LED work light bar. Flood/spot combo. For off-road, Hilux, 4Runner. Waterproof IP68.", price: "155.00", brand: "Nilight", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "JJ-LGT-005", quantity: 25 },
  { vendorId: JIJI, categoryId: 4, name: "Toyota Land Cruiser Fog Light (Right)", description: "Used right fog light from LC200 2012. Perfectly working. Bracket included.", price: "180.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Land Cruiser", yearFrom: 2008, yearTo: 2015, sku: "JJ-LGT-006", quantity: 1 },
  { vendorId: JIJI, categoryId: 4, name: "VW Golf Headlight (Left, Aftermarket)", description: "Aftermarket left headlight for Golf Mk6. Chrome inner, clear lens. Projector beam.", price: "320.00", brand: "Depo", condition: "new", vehicleMake: "Volkswagen", vehicleModel: "Golf", yearFrom: 2009, yearTo: 2013, sku: "JJ-LGT-007", quantity: 5 },
  { vendorId: JIJI, categoryId: 4, name: "Hyundai Accent Third Brake Light", description: "New high-mount LED third brake light for Accent 2012-2018. Direct fit, no cutting.", price: "95.00", brand: "Depo", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Accent", yearFrom: 2012, yearTo: 2018, sku: "JJ-LGT-008", quantity: 18 },
  { vendorId: JIJI, categoryId: 4, name: "Ford Ranger LED Side Marker Lights", description: "Pair of LED side marker lights for Ranger 2012-2022. Amber front, red rear. Easy clip-in.", price: "85.00", brand: "Anzo", condition: "new", vehicleMake: "Ford", vehicleModel: "Ranger", yearFrom: 2012, yearTo: 2022, sku: "JJ-LGT-009", quantity: 22 },
  { vendorId: JIJI, categoryId: 4, name: "Toyota Highlander LED Reverse Light Bulb", description: "T15 LED reverse light bulb. White 6000K. 3X brighter than halogen. Fits most Highlander models.", price: "45.00", brand: "Sylvania", condition: "new", vehicleMake: "Toyota", vehicleModel: "Highlander", yearFrom: 2008, yearTo: 2020, sku: "JJ-LGT-010", quantity: 50 },
];

// ─── CAT 5: Cooling System ────────────────────────────────────────────────────

const cat5_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 5, name: "Toyota Corolla Radiator (1.6L/1.8L)", description: "Aluminium core radiator for Corolla. 2-row design for superior cooling. Ghana climate tested. Fits AT & MT.", price: "480.00", brand: "Spectra Premium", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2002, yearTo: 2014, sku: "TN-COL-001", oemPartNumber: "16400-22110", quantity: 12, featured: true },
  { vendorId: TONATON, categoryId: 5, name: "Honda CR-V AC Compressor", description: "New AC compressor for CR-V 2.0L & 2.4L. Pre-filled with PAG oil. Includes new clutch and gaskets.", price: "1250.00", brand: "Denso", condition: "new", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2007, yearTo: 2016, sku: "TN-COL-002", oemPartNumber: "38810-RZA-006", quantity: 6 },
  { vendorId: TONATON, categoryId: 5, name: "Toyota Camry Thermostat Kit", description: "OEM thermostat with housing for Camry 2.4L 2AZ. Prevents overheating. Includes O-ring seal.", price: "145.00", brand: "Gates", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2017, sku: "TN-COL-003", oemPartNumber: "90916-03129", quantity: 30 },
  { vendorId: TONATON, categoryId: 5, name: "Hyundai Tucson Radiator Fan Motor", description: "Electric cooling fan motor for Tucson 2.0L. Maintains optimal engine temp in traffic. Direct fit.", price: "420.00", brand: "Denso", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2010, yearTo: 2020, sku: "TN-COL-004", quantity: 9 },
  { vendorId: TONATON, categoryId: 5, name: "Nissan X-Trail AC Condenser", description: "Parallel flow AC condenser for X-Trail T31/T32. Maximum heat rejection for Ghana climate.", price: "560.00", brand: "Spectra", condition: "new", vehicleMake: "Nissan", vehicleModel: "X-Trail", yearFrom: 2007, yearTo: 2018, sku: "TN-COL-005", quantity: 8 },
  { vendorId: TONATON, categoryId: 5, name: "Toyota RAV4 Intercooler", description: "Bar-plate intercooler for RAV4 2.0L turbo (2019+). 30% more cooling capacity. Direct-fit.", price: "890.00", brand: "Mishimoto", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2019, yearTo: 2024, sku: "TN-COL-006", quantity: 4 },
  { vendorId: TONATON, categoryId: 5, name: "Universal Coolant Reservoir Expansion Tank", description: "1.5L universal coolant overflow reservoir with cap. Fits most vehicles. OEM-style translucent.", price: "115.00", brand: "Dorman", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2022, sku: "TN-COL-007", quantity: 35 },
  { vendorId: TONATON, categoryId: 5, name: "Toyota Hilux Heater Core", description: "Heater matrix/core for Hilux Vigo. Aluminium construction for durability. Fix AC that blows cold only.", price: "380.00", brand: "Spectra", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2015, sku: "TN-COL-008", oemPartNumber: "87107-0K020", quantity: 7 },
  { vendorId: TONATON, categoryId: 5, name: "Honda Accord Radiator Cap (1.1 Bar)", description: "OEM-spec radiator cap for Accord. 1.1 bar pressure. Prevents coolant loss. Fits most Honda models.", price: "45.00", brand: "Stant", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2003, yearTo: 2020, sku: "TN-COL-009", quantity: 80 },
  { vendorId: TONATON, categoryId: 5, name: "Hyundai Santa Fe Oil Cooler", description: "Engine oil cooler for Santa Fe 2.2L CRDi diesel. Prevents oil overheating under load. OEM fit.", price: "620.00", brand: "Mahle", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Santa Fe", yearFrom: 2010, yearTo: 2018, sku: "TN-COL-010", quantity: 5 },
];

const cat5_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 5, name: "Toyota Camry Radiator (Used)", description: "Used radiator from Camry 2012, good condition. No leaks, fins straight. Ideal for budget repair.", price: "220.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2014, sku: "JJ-COL-001", quantity: 2 },
  { vendorId: JIJI, categoryId: 5, name: "Honda Civic AC Compressor (Rebuilt)", description: "Rebuilt AC compressor for Civic 1.8L. New seals, pressure-tested. Much cheaper than new.", price: "580.00", brand: "Honda OEM", condition: "refurbished", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2006, yearTo: 2015, sku: "JJ-COL-002", quantity: 3, featured: true },
  { vendorId: JIJI, categoryId: 5, name: "Toyota Corolla Radiator Hose Set", description: "Upper and lower radiator hoses for Corolla 1.6L & 1.8L. Silicone reinforced. Set of 2.", price: "125.00", brand: "Gates", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2015, sku: "JJ-COL-003", quantity: 28 },
  { vendorId: JIJI, categoryId: 5, name: "Nissan Pathfinder AC Condenser", description: "Used AC condenser from Pathfinder 2009. Pressure-tested. No leaks. Good working order.", price: "250.00", brand: "Nissan OEM", condition: "used", vehicleMake: "Nissan", vehicleModel: "Pathfinder", yearFrom: 2005, yearTo: 2012, sku: "JJ-COL-004", quantity: 1 },
  { vendorId: JIJI, categoryId: 5, name: "Hyundai Elantra Thermostat", description: "New thermostat for Elantra 1.8L & 2.0L. Prevents overheating. Includes housing bolt set.", price: "130.00", brand: "Behr", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Elantra", yearFrom: 2011, yearTo: 2020, sku: "JJ-COL-005", quantity: 22 },
  { vendorId: JIJI, categoryId: 5, name: "Ford Ranger Radiator (2.2L/3.2L TDCI)", description: "New aluminium radiator for Ranger TDCI. Dual-pass design. Fits manual and automatic gearbox models.", price: "680.00", brand: "Spectra", condition: "new", vehicleMake: "Ford", vehicleModel: "Ranger", yearFrom: 2012, yearTo: 2022, sku: "JJ-COL-006", quantity: 6 },
  { vendorId: JIJI, categoryId: 5, name: "Toyota Land Cruiser AC Evaporator", description: "Used AC evaporator from LC100 2005. Tested leak-free. Good condition for restoration build.", price: "450.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Land Cruiser", yearFrom: 2000, yearTo: 2007, sku: "JJ-COL-007", quantity: 1 },
  { vendorId: JIJI, categoryId: 5, name: "BMW 5 Series Expansion Tank", description: "New coolant expansion reservoir for BMW F10 520i/528i. OE quality, pressure-rated cap included.", price: "210.00", brand: "Dorman", condition: "new", vehicleMake: "BMW", vehicleModel: "5 Series", yearFrom: 2010, yearTo: 2016, sku: "JJ-COL-008", quantity: 10 },
  { vendorId: JIJI, categoryId: 5, name: "Kia Sportage Radiator Fan Assembly", description: "New twin radiator fan assembly for Sportage 2011-2016. Direct replacement. 12-month warranty.", price: "380.00", brand: "Behr", condition: "new", vehicleMake: "Kia", vehicleModel: "Sportage", yearFrom: 2011, yearTo: 2016, sku: "JJ-COL-009", quantity: 7 },
  { vendorId: JIJI, categoryId: 5, name: "Universal Radiator Cap 0.9 Bar", description: "Universal radiator/coolant cap 0.9 bar. Fits Toyota, Honda, Nissan and Hyundai small tanks.", price: "35.00", brand: "Stant", condition: "new", vehicleMake: "Toyota", vehicleModel: "Yaris/Vitz", yearFrom: 2005, yearTo: 2020, sku: "JJ-COL-010", quantity: 100 },
];

// ─── CAT 6: Filters & Fluids ──────────────────────────────────────────────────

const cat6_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 6, name: "Toyota Oil Filter (10-pack)", description: "Genuine-quality oil filters for Toyota 1.6L-3.5L engines. Double anti-drain valve. 10 units.", price: "195.00", brand: "Bosch", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "TN-FLT-001", oemPartNumber: "90915-YZZB2", quantity: 100, featured: true },
  { vendorId: TONATON, categoryId: 6, name: "Honda Cabin/Pollen Filter", description: "Activated carbon cabin air filter for Honda Accord, Civic, CR-V. Blocks dust, pollen and odours.", price: "75.00", brand: "Fram", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2020, sku: "TN-FLT-002", oemPartNumber: "80292-SDA-A01", quantity: 60 },
  { vendorId: TONATON, categoryId: 6, name: "Toyota Hilux Fuel Filter (Diesel)", description: "Diesel fuel filter for Hilux 2.5D & 3.0D. Water separator with drain plug. 30,000km service life.", price: "185.00", brand: "Bosch", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "TN-FLT-003", oemPartNumber: "23390-0L010", quantity: 40 },
  { vendorId: TONATON, categoryId: 6, name: "Castrol GTX 10W-40 Engine Oil (4L)", description: "Mineral motor oil for older high-mileage petrol engines. Protects against sludge and wear. 4-litre.", price: "165.00", brand: "Castrol", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2012, sku: "TN-FLT-004", quantity: 80 },
  { vendorId: TONATON, categoryId: 6, name: "Mobil 1 5W-30 Fully Synthetic (4L)", description: "Full synthetic oil for modern Toyota, Honda and Hyundai petrol engines. 15,000km drain interval.", price: "285.00", brand: "Mobil 1", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2013, yearTo: 2022, sku: "TN-FLT-005", quantity: 70 },
  { vendorId: TONATON, categoryId: 6, name: "Hyundai/Kia Air Filter", description: "High-flow air filter for Hyundai Tucson, Elantra, Kia Sportage and Rio 1.6L & 2.0L. OEM fit.", price: "95.00", brand: "Mahle", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2010, yearTo: 2022, sku: "TN-FLT-006", oemPartNumber: "28113-2S000", quantity: 55 },
  { vendorId: TONATON, categoryId: 6, name: "Honda ATF Dexron III Transmission Fluid (4L)", description: "Automatic transmission fluid for Honda SLAHS ATF. Smooth shifts, prevents wear. 4-litre bottle.", price: "195.00", brand: "Prestone", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2003, yearTo: 2017, sku: "TN-FLT-007", quantity: 40 },
  { vendorId: TONATON, categoryId: 6, name: "Toyota Super Long-Life Coolant (2L)", description: "Pink super long-life coolant for Toyota. Ready-to-use 50/50 dilution. 5-year / 100k km protection.", price: "120.00", brand: "Toyota Genuine", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "TN-FLT-008", oemPartNumber: "08889-80109", quantity: 65 },
  { vendorId: TONATON, categoryId: 6, name: "DOT 4 Brake Fluid (500ml)", description: "High-temp DOT 4 brake fluid. Dry boiling point 230°C. Suitable for all disc brake systems.", price: "55.00", brand: "Bosch", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "TN-FLT-009", quantity: 120 },
  { vendorId: TONATON, categoryId: 6, name: "Toyota Transmission Filter Kit (4-Speed AT)", description: "Automatic transmission filter and pan gasket for Toyota A40/A140 4-speed. Includes filter, gasket and pan bolts.", price: "210.00", brand: "Beck Arnley", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2002, yearTo: 2011, sku: "TN-FLT-010", quantity: 25 },
];

const cat6_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 6, name: "Total Quartz 10W-40 Engine Oil (4L)", description: "Semi-synthetic engine oil for petrol engines. 10,000km drain interval. Good for Ghanaian conditions.", price: "155.00", brand: "Total", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2022, sku: "JJ-FLT-001", quantity: 90, featured: true },
  { vendorId: JIJI, categoryId: 6, name: "Nissan Oil Filter (Pack of 5)", description: "OEM-spec oil filters for Nissan petrol engines 1.6L-2.5L. Pack of 5. Great value.", price: "95.00", brand: "Purolator", condition: "new", vehicleMake: "Nissan", vehicleModel: "Almera", yearFrom: 2000, yearTo: 2020, sku: "JJ-FLT-002", quantity: 50 },
  { vendorId: JIJI, categoryId: 6, name: "Honda Air Filter — Civic/Accord/CR-V", description: "Paper air filter for Honda 1.8L & 2.4L. Easy 5-minute replacement. Restores power and fuel economy.", price: "65.00", brand: "K&N OEM Style", condition: "new", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2006, yearTo: 2018, sku: "JJ-FLT-003", quantity: 70 },
  { vendorId: JIJI, categoryId: 6, name: "Toyota Hilux Diesel Fuel Filter", description: "Spin-on diesel fuel filter for Hilux 2.5D & 3.0D. Protects injectors from water and contamination.", price: "160.00", brand: "Sakura", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "JJ-FLT-004", quantity: 35 },
  { vendorId: JIJI, categoryId: 6, name: "Shell Helix HX3 15W-40 (4L)", description: "Mineral engine oil ideal for older petrol and diesel engines. Ghana budget favourite. 4-litre bottle.", price: "130.00", brand: "Shell", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2015, sku: "JJ-FLT-005", quantity: 100 },
  { vendorId: JIJI, categoryId: 6, name: "Power Steering Fluid (1L)", description: "Universal power steering fluid. Stops rack rattle and moaning. Compatible with most Japanese power steering systems.", price: "50.00", brand: "Prestone", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2020, sku: "JJ-FLT-006", quantity: 80 },
  { vendorId: JIJI, categoryId: 6, name: "Ford Ranger Transmission Filter (6-Speed)", description: "Automatic transmission filter for Ranger 6R80 6-speed. Includes pan gasket. Prevents slipping.", price: "235.00", brand: "ACDelco", condition: "new", vehicleMake: "Ford", vehicleModel: "Ranger", yearFrom: 2012, yearTo: 2022, sku: "JJ-FLT-007", quantity: 14 },
  { vendorId: JIJI, categoryId: 6, name: "Toyota Cabin Filter — Camry/RAV4", description: "Cabin pollen filter for Camry and RAV4. Blocks fine dust and pollen. Replace every 15,000 km.", price: "70.00", brand: "Fram", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2020, sku: "JJ-FLT-008", quantity: 55 },
  { vendorId: JIJI, categoryId: 6, name: "Windshield Washer Fluid Concentrate (500ml)", description: "Concentrated washer fluid. Mix 1:10. Cleans rain, mud and dust off windscreen instantly.", price: "25.00", brand: "Rain-X", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "JJ-FLT-009", quantity: 200 },
  { vendorId: JIJI, categoryId: 6, name: "DOT 3 Brake Fluid (500ml)", description: "Standard DOT 3 brake fluid for drum and disc brake systems. Budget-friendly. Suitable for most vehicles.", price: "42.00", brand: "Bendix", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2022, sku: "JJ-FLT-010", quantity: 150 },
];

// ─── CAT 7: Transmission & Clutch ────────────────────────────────────────────

const cat7_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 7, name: "Toyota Corolla Clutch Kit (1.6L)", description: "Complete clutch kit for Corolla E120/E140 1.6L. Includes disc, pressure plate and release bearing.", price: "650.00", brand: "Exedy", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2014, sku: "TN-TRN-001", oemPartNumber: "TSK-1756", quantity: 15, featured: true },
  { vendorId: TONATON, categoryId: 7, name: "Honda Accord Torque Converter", description: "Remanufactured torque converter for Accord 2.4L & 3.5L. Balanced and pressure-tested. 12-month warranty.", price: "1580.00", brand: "Sonnax", condition: "refurbished", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2017, sku: "TN-TRN-002", quantity: 4 },
  { vendorId: TONATON, categoryId: 7, name: "Toyota Hilux Manual Gearbox Mount", description: "Rear gearbox mount for Hilux manual 1KD/2KD diesel. Vibration-dampening rubber. Direct bolt-on.", price: "195.00", brand: "Febest", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2015, sku: "TN-TRN-003", oemPartNumber: "58200-35120", quantity: 20 },
  { vendorId: TONATON, categoryId: 7, name: "Hyundai Tucson Clutch Disc", description: "Clutch disc for Tucson 2.0L manual. High-friction material. Replaces worn or slipping discs.", price: "285.00", brand: "Valeo", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2010, yearTo: 2018, sku: "TN-TRN-004", quantity: 12 },
  { vendorId: TONATON, categoryId: 7, name: "Nissan X-Trail Transfer Case", description: "Used transfer case from X-Trail 2.0L 4WD. Thoroughly tested, clean condition. Swap ready.", price: "2200.00", brand: "Nissan OEM", condition: "used", vehicleMake: "Nissan", vehicleModel: "X-Trail", yearFrom: 2007, yearTo: 2015, sku: "TN-TRN-005", quantity: 2 },
  { vendorId: TONATON, categoryId: 7, name: "Toyota Camry Shift Cable", description: "Gear selector cable for Camry 2.4L & 2.5L automatic. Restores accurate gear selection. Includes clips.", price: "265.00", brand: "Dorman", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2017, sku: "TN-TRN-006", oemPartNumber: "33820-06100", quantity: 14 },
  { vendorId: TONATON, categoryId: 7, name: "Honda CR-V Differential (Rear)", description: "Remanufactured rear differential for CR-V AWD. Ratio matched. Includes new seals and fluid.", price: "2850.00", brand: "Honda OEM", condition: "refurbished", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2007, yearTo: 2016, sku: "TN-TRN-007", quantity: 2 },
  { vendorId: TONATON, categoryId: 7, name: "Toyota Hilux Propeller Shaft (Front)", description: "Front prop shaft for Hilux Vigo 4WD. Dynamic balanced, new U-joints. Ready to install.", price: "1350.00", brand: "Cardone", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2015, sku: "TN-TRN-008", oemPartNumber: "37100-0K041", quantity: 5 },
  { vendorId: TONATON, categoryId: 7, name: "Kia Sportage Release Bearing", description: "Clutch release bearing for Sportage 2.0L manual. Smooth engagement, quiet. Matches Exedy kit.", price: "165.00", brand: "Sachs", condition: "new", vehicleMake: "Kia", vehicleModel: "Sportage", yearFrom: 2011, yearTo: 2020, sku: "TN-TRN-009", quantity: 22 },
  { vendorId: TONATON, categoryId: 7, name: "Toyota Corolla Automatic Transmission Assembly", description: "Used automatic transmission (U340E) from Corolla 2009. 120,000km, shifted perfectly before removal.", price: "3500.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2007, yearTo: 2013, sku: "TN-TRN-010", quantity: 1 },
];

const cat7_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 7, name: "Toyota Camry Clutch Kit (2.4L)", description: "Complete clutch kit for Camry 2.4L 2AZ-FE. Disc, pressure plate, bearing. Exedy OEM grade.", price: "720.00", brand: "Exedy", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2017, sku: "JJ-TRN-001", quantity: 8, featured: true },
  { vendorId: JIJI, categoryId: 7, name: "Honda Civic Manual Gearbox", description: "Used 5-speed gearbox from Civic FD 2010 1.8L. Smooth all gears. 80,000km. Ready for swap.", price: "1800.00", brand: "Honda OEM", condition: "used", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2006, yearTo: 2012, sku: "JJ-TRN-002", quantity: 1 },
  { vendorId: JIJI, categoryId: 7, name: "Hyundai Sonata Clutch Pressure Plate", description: "New clutch pressure plate for Sonata 2.0L manual. Diaphragm spring type. OEM dimensions.", price: "310.00", brand: "Sachs", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Sonata", yearFrom: 2010, yearTo: 2015, sku: "JJ-TRN-003", quantity: 9 },
  { vendorId: JIJI, categoryId: 7, name: "Mitsubishi L200 Transfer Case", description: "Used transfer case from L200 2010 4WD diesel. All gears engage correctly. Clean unit.", price: "2400.00", brand: "Mitsubishi OEM", condition: "used", vehicleMake: "Mitsubishi", vehicleModel: "L200/Triton", yearFrom: 2006, yearTo: 2014, sku: "JJ-TRN-004", quantity: 1 },
  { vendorId: JIJI, categoryId: 7, name: "Toyota RAV4 Gearbox Mount (AT)", description: "Automatic transmission mount for RAV4 2.0L & 2.5L. Stops gear surging. Direct OEM replacement.", price: "220.00", brand: "Febest", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2006, yearTo: 2018, sku: "JJ-TRN-005", quantity: 16 },
  { vendorId: JIJI, categoryId: 7, name: "Kia Sportage Propeller Shaft", description: "Used rear propeller shaft from Sportage 2015 2.4L AWD. Balanced. U-joints good.", price: "580.00", brand: "Kia OEM", condition: "used", vehicleMake: "Kia", vehicleModel: "Sportage", yearFrom: 2011, yearTo: 2016, sku: "JJ-TRN-006", quantity: 1 },
  { vendorId: JIJI, categoryId: 7, name: "Honda Accord Torque Converter (Used)", description: "Pulled from Accord 2011 3.5L with 90,000km. Lock-up clutch tested OK. Budget transmission fix.", price: "650.00", brand: "Honda OEM", condition: "used", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2013, sku: "JJ-TRN-007", quantity: 1 },
  { vendorId: JIJI, categoryId: 7, name: "Nissan Navara Rear Differential", description: "Used rear differential from Navara D40 2010. 38/9 ratio. Axle output flanges included.", price: "1950.00", brand: "Nissan OEM", condition: "used", vehicleMake: "Nissan", vehicleModel: "Navara", yearFrom: 2006, yearTo: 2015, sku: "JJ-TRN-008", quantity: 1 },
  { vendorId: JIJI, categoryId: 7, name: "Hyundai Tucson Shift Cable", description: "Gear selector shift cable for Tucson 2.0L automatic. Corrects hesitation or stuck gear selector.", price: "240.00", brand: "Dorman", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2010, yearTo: 2020, sku: "JJ-TRN-009", quantity: 10 },
  { vendorId: JIJI, categoryId: 7, name: "Toyota Hilux Clutch Kit 2.5D (Complete)", description: "Full clutch replacement kit for Hilux 2.5L diesel. Heavy-duty for taxi and load carrying use.", price: "850.00", brand: "Valeo", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2015, sku: "JJ-TRN-010", quantity: 6 },
];

// ─── CAT 8: Electrical & Electronics ─────────────────────────────────────────

const cat8_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 8, name: "65Ah AGM Car Battery — Toyota/Honda/Nissan", description: "65Ah AGM maintenance-free battery. Fits most Japanese sedans and SUVs. 24-month warranty. CCA 580A.", price: "680.00", brand: "Varta", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "TN-ELC-001", quantity: 30, featured: true },
  { vendorId: TONATON, categoryId: 8, name: "Toyota Corolla ABS Module (Used)", description: "Pulled ABS control module from Corolla 2012. Tested and working. Matched to VIN available.", price: "420.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2008, yearTo: 2013, sku: "TN-ELC-002", quantity: 3 },
  { vendorId: TONATON, categoryId: 8, name: "Honda Accord Window Regulator (Front Left)", description: "Power window regulator with motor for Accord 2008-2015. Resolves slow or stuck front window.", price: "290.00", brand: "Dorman", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2015, sku: "TN-ELC-003", oemPartNumber: "72250-TA0-H01", quantity: 14 },
  { vendorId: TONATON, categoryId: 8, name: "Toyota Hilux ECU (Engine Control Unit)", description: "Used ECU for Hilux 2.7L VVT-i petrol 2005-2012. Plug-and-play, no coding needed for same VIN.", price: "650.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2012, sku: "TN-ELC-004", quantity: 2 },
  { vendorId: TONATON, categoryId: 8, name: "Bosch O2 Lambda Sensor (Universal Wideband)", description: "Universal wideband oxygen sensor. Fits Toyota, Honda, Hyundai 4-pin vehicles. Clears P0135, P0141.", price: "235.00", brand: "Bosch", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2020, sku: "TN-ELC-005", oemPartNumber: "0258003477", quantity: 25 },
  { vendorId: TONATON, categoryId: 8, name: "Hyundai Tucson Door Lock Actuator", description: "Rear door lock actuator for Tucson 2010-2020. Replaces faulty central locking. Left or right.", price: "185.00", brand: "Dorman", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2010, yearTo: 2020, sku: "TN-ELC-006", quantity: 20 },
  { vendorId: TONATON, categoryId: 8, name: "Toyota RAV4 Crankshaft Position Sensor", description: "Crank position sensor for RAV4 2.0L & 2.5L. Fixes no-start and engine stalling. Direct plug-in.", price: "175.00", brand: "Denso", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2006, yearTo: 2018, sku: "TN-ELC-007", oemPartNumber: "90919-05028", quantity: 18 },
  { vendorId: TONATON, categoryId: 8, name: "90Ah Battery — Mercedes/BMW/VW", description: "Premium 90Ah battery for German cars with high electrical load. AGM start-stop compatible. CCA 720A.", price: "950.00", brand: "Bosch", condition: "new", vehicleMake: "BMW", vehicleModel: "3 Series", yearFrom: 2010, yearTo: 2022, sku: "TN-ELC-008", quantity: 15 },
  { vendorId: TONATON, categoryId: 8, name: "Toyota Camry Ignition Switch", description: "Ignition switch with key cylinder for Camry 2007-2011. Resolves intermittent no-start issues.", price: "320.00", brand: "Standard Motor", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2011, sku: "TN-ELC-009", oemPartNumber: "84450-06090", quantity: 8 },
  { vendorId: TONATON, categoryId: 8, name: "Universal MAF Sensor Cleaner (400ml)", description: "CRC Mass Air Flow sensor cleaner. Removes oil film from MAF wire. Fixes rough idle and poor MPG.", price: "85.00", brand: "CRC", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "TN-ELC-010", quantity: 50 },
];

const cat8_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 8, name: "75Ah Sealed Battery — Universal Fit", description: "Maintenance-free 75Ah battery. Good for Toyota, Honda, Nissan SUVs. 18-month warranty.", price: "550.00", brand: "Luminous", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2006, yearTo: 2022, sku: "JJ-ELC-001", quantity: 20, featured: true },
  { vendorId: JIJI, categoryId: 8, name: "Toyota Corolla Alternator (Used, 80A)", description: "Used alternator from Corolla 2012 1.8L. Output tested at 80A. Good for another 80,000km.", price: "280.00", brand: "Denso", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2008, yearTo: 2016, sku: "JJ-ELC-002", quantity: 4 },
  { vendorId: JIJI, categoryId: 8, name: "Hyundai Elantra Wiring Harness (Engine Bay)", description: "Used engine bay wiring harness from Elantra 2013 2.0L. Intact connectors, no cuts or burns.", price: "420.00", brand: "Hyundai OEM", condition: "used", vehicleMake: "Hyundai", vehicleModel: "Elantra", yearFrom: 2011, yearTo: 2016, sku: "JJ-ELC-003", quantity: 1 },
  { vendorId: JIJI, categoryId: 8, name: "Honda Civic Blower Motor", description: "New heater blower motor for Civic 2006-2015. Fixes weak or no airflow from vents. Includes resistor.", price: "195.00", brand: "Dorman", condition: "new", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2006, yearTo: 2015, sku: "JJ-ELC-004", quantity: 12 },
  { vendorId: JIJI, categoryId: 8, name: "Nissan X-Trail ABS Wheel Speed Sensor", description: "New front ABS sensor for X-Trail. Fixes ABS warning light and traction control errors.", price: "155.00", brand: "Bosch", condition: "new", vehicleMake: "Nissan", vehicleModel: "X-Trail", yearFrom: 2007, yearTo: 2018, sku: "JJ-ELC-005", quantity: 16 },
  { vendorId: JIJI, categoryId: 8, name: "Toyota Hilux Horn (12V Dual Tone)", description: "Dual-tone 12V car horn for Hilux. 110dB loud. Direct replacement. Plug-and-play wiring.", price: "75.00", brand: "Hella", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "JJ-ELC-006", quantity: 30 },
  { vendorId: JIJI, categoryId: 8, name: "Universal Relay 12V 40A (Pack of 5)", description: "12V 40A 5-pin relays for AC, fans, horns, pumps. Common automotive relay. Pack of 5.", price: "55.00", brand: "Bosch", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "JJ-ELC-007", quantity: 80 },
  { vendorId: JIJI, categoryId: 8, name: "Mercedes C200 Fuse Box (Used)", description: "Used interior fuse box from C200 W204 2012. All fuses intact. Clean condition. Check fitment.", price: "360.00", brand: "Mercedes OEM", condition: "used", vehicleMake: "Mercedes-Benz", vehicleModel: "C-Class", yearFrom: 2007, yearTo: 2014, sku: "JJ-ELC-008", quantity: 1 },
  { vendorId: JIJI, categoryId: 8, name: "Toyota Camry MAP Sensor", description: "Manifold absolute pressure sensor for Camry 2.4L. Fixes poor idle, rich running and low power.", price: "185.00", brand: "Denso", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2007, yearTo: 2017, sku: "JJ-ELC-009", oemPartNumber: "89421-28060", quantity: 10 },
  { vendorId: JIJI, categoryId: 8, name: "Starter Motor — Nissan Almera (Used)", description: "Used starter from Almera 1.6L 2010. Tested and working. Bench-tested before sale.", price: "180.00", brand: "Mitsubishi Electric", condition: "used", vehicleMake: "Nissan", vehicleModel: "Almera", yearFrom: 2006, yearTo: 2014, sku: "JJ-ELC-010", quantity: 2 },
];

// ─── CAT 9: Wheels & Tires ───────────────────────────────────────────────────

const cat9_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 9, name: "195/65R15 All-Season Tire — Toyota Corolla", description: "195/65R15 91H all-season tire for Corolla, Civic, Elantra. Wet grip rated B. M+S rated.", price: "320.00", brand: "Bridgestone Ecopia", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "TN-WHL-001", quantity: 40, featured: true },
  { vendorId: TONATON, categoryId: 9, name: "265/65R17 SUV Tire — Toyota RAV4/Fortuner", description: "265/65R17 all-terrain tire for SUVs and pickups. Excellent grip on Ghana's wet and dirt roads.", price: "680.00", brand: "Michelin LTX A/T2", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2006, yearTo: 2022, sku: "TN-WHL-002", quantity: 20 },
  { vendorId: TONATON, categoryId: 9, name: "15-Inch Alloy Rim (Set of 4) — 5×114.3 PCD", description: "15-inch 6-spoke silver alloy rims. 5×114.3 bolt pattern. Fits Corolla, Civic, Elantra. With center caps.", price: "1800.00", brand: "Enkei", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2020, sku: "TN-WHL-003", quantity: 8 },
  { vendorId: TONATON, categoryId: 9, name: "17-Inch Alloy Rims (Set of 4) — 5×114.3", description: "17-inch 10-spoke gunmetal alloy rims for Honda CR-V, RAV4, Tucson. ET45, 7.5J wide.", price: "2800.00", brand: "Rays", condition: "new", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2007, yearTo: 2022, sku: "TN-WHL-004", quantity: 5 },
  { vendorId: TONATON, categoryId: 9, name: "Toyota Hilux Spare Tire (265/70R16)", description: "New spare tire mounted on OEM steel rim for Hilux. 265/70R16. Correct spec for Hilux Vigo/Revo.", price: "780.00", brand: "Bridgestone Dueler", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "TN-WHL-005", quantity: 10 },
  { vendorId: TONATON, categoryId: 9, name: "Wheel Cover/Hubcap Set — 15-inch (Pack of 4)", description: "Universal 15-inch black hubcaps. ABS plastic, secure clip-on. Fits most sedans with steel rims.", price: "95.00", brand: "Pilot", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2022, sku: "TN-WHL-006", quantity: 30 },
  { vendorId: TONATON, categoryId: 9, name: "TPMS Sensor Kit (Set of 4) — Universal 433MHz", description: "Aftermarket TPMS sensors 433MHz. Works with Toyota, Honda, Hyundai, Kia TPMS systems. Easy programming.", price: "280.00", brand: "Autel", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2014, yearTo: 2022, sku: "TN-WHL-007", quantity: 15 },
  { vendorId: TONATON, categoryId: 9, name: "Lug Nut Set (20 Pieces) — M12×1.5 Chrome", description: "Chrome cone seat lug nuts M12×1.5 thread. 20-piece set for 5-lug vehicles. Fits Toyota, Honda, Kia.", price: "85.00", brand: "Gorilla", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "TN-WHL-008", quantity: 50 },
  { vendorId: TONATON, categoryId: 9, name: "205/60R16 Tire — Honda Accord/Nissan Altima", description: "205/60R16 92H summer tire. Low rolling resistance, good wet handling. AA/A rated.", price: "395.00", brand: "Continental EcoContact", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2020, sku: "TN-WHL-009", quantity: 24 },
  { vendorId: TONATON, categoryId: 9, name: "5mm Wheel Spacer Kit — 5×114.3 (Set of 4)", description: "5mm hub-centric wheel spacers. CNC machined billet aluminium. M12×1.5 thread. For Corolla, Camry, Civic.", price: "155.00", brand: "H&R", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "TN-WHL-010", quantity: 18 },
];

const cat9_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 9, name: "195/65R15 Used Tires (Set of 4)", description: "Used 195/65R15 tyres with 50-60% tread. Good for daily commute. Balanced and ready to mount.", price: "480.00", brand: "Bridgestone", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2020, sku: "JJ-WHL-001", quantity: 4, featured: true },
  { vendorId: JIJI, categoryId: 9, name: "16-Inch Steel Rims (Set of 4) — Hilux", description: "Used OEM steel rims from Toyota Hilux. 16-inch, 6-lug 6×139.7. Good condition, no bends.", price: "480.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2015, sku: "JJ-WHL-002", quantity: 1 },
  { vendorId: JIJI, categoryId: 9, name: "225/65R17 All-Terrain Tire", description: "New all-terrain 225/65R17 for SUVs. Aggressive tread pattern. Good on tar and gravel roads.", price: "520.00", brand: "Toyo Open Country", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Santa Fe", yearFrom: 2007, yearTo: 2020, sku: "JJ-WHL-003", quantity: 16 },
  { vendorId: JIJI, categoryId: 9, name: "Honda CR-V 17-Inch OEM Alloy Rim", description: "Single used OEM 17-inch alloy from CR-V 2014. 5×114.3 PCD. Good condition, one small curb mark.", price: "220.00", brand: "Honda OEM", condition: "used", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2012, yearTo: 2018, sku: "JJ-WHL-004", quantity: 1 },
  { vendorId: JIJI, categoryId: 9, name: "215/70R16 Light Truck Tire", description: "New 215/70R16 LT tire for minibuses and light trucks. Highway terrain, long tread life.", price: "440.00", brand: "Kumho Road Venture", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hiace", yearFrom: 2005, yearTo: 2022, sku: "JJ-WHL-005", quantity: 18 },
  { vendorId: JIJI, categoryId: 9, name: "Wheel Stud Kit (M12×1.5, Set of 10)", description: "Replacement wheel studs M12×1.5. For Toyota, Honda and Nissan. Press-in type. Pack of 10.", price: "65.00", brand: "Dorman", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2022, sku: "JJ-WHL-006", quantity: 40 },
  { vendorId: JIJI, categoryId: 9, name: "TPMS Sensors (Set of 4) — BMW/Mercedes", description: "New 433MHz TPMS sensors for BMW 3, 5, 7 Series and Mercedes C, E, GLE. Easy clone programming.", price: "380.00", brand: "Schrader", condition: "new", vehicleMake: "BMW", vehicleModel: "5 Series", yearFrom: 2010, yearTo: 2022, sku: "JJ-WHL-007", quantity: 8 },
  { vendorId: JIJI, categoryId: 9, name: "185/65R14 Budget Tire — Economy Car", description: "New 185/65R14 tire. Budget brand, great for trotro, taxis and city use. Good wet traction.", price: "230.00", brand: "Linglong", condition: "new", vehicleMake: "Toyota", vehicleModel: "Yaris/Vitz", yearFrom: 2005, yearTo: 2020, sku: "JJ-WHL-008", quantity: 25 },
  { vendorId: JIJI, categoryId: 9, name: "Nissan Pathfinder Spare Tire (265/65R17)", description: "Used 265/65R17 spare tire from Pathfinder 2010. 80% tread. Still in spare carrier bracket.", price: "250.00", brand: "Bridgestone Dueler", condition: "used", vehicleMake: "Nissan", vehicleModel: "Pathfinder", yearFrom: 2005, yearTo: 2012, sku: "JJ-WHL-009", quantity: 1 },
  { vendorId: JIJI, categoryId: 9, name: "16-Inch Hub Cap Set (Pack of 4)", description: "Universal 16-inch wheel covers for steel rims. Silver finish, full face design. Secure ring clip.", price: "110.00", brand: "Pilot", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2003, yearTo: 2017, sku: "JJ-WHL-010", quantity: 25 },
];

// ─── CAT 10: Interior & Accessories ──────────────────────────────────────────

const cat10_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 10, name: "Toyota Corolla Seat Cover Set (Full)", description: "Custom-fit leather seat cover set for Corolla 2014-2020. Airbag-compatible. Black with red stitching.", price: "580.00", brand: "Clazzio", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2014, yearTo: 2020, sku: "TN-INT-001", quantity: 12, featured: true },
  { vendorId: TONATON, categoryId: 10, name: "All-Weather Floor Mat Set — Universal", description: "Heavy-duty rubber floor mats. 4-piece set. Trimmable to fit most cars. Anti-slip backing.", price: "175.00", brand: "WeatherTech", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-INT-002", quantity: 30 },
  { vendorId: TONATON, categoryId: 10, name: "Honda Accord Steering Wheel (Leather)", description: "OEM-style leather-wrapped steering wheel for Accord 2008-2017. Heated option available. 38cm diameter.", price: "420.00", brand: "Momo", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2017, sku: "TN-INT-003", quantity: 8 },
  { vendorId: TONATON, categoryId: 10, name: "Toyota RAV4 Seat Belt Assembly", description: "New front seat belt with pre-tensioner for RAV4. Includes retractor and latch. Left or right.", price: "350.00", brand: "TRW", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2006, yearTo: 2018, sku: "TN-INT-004", oemPartNumber: "73210-0R060", quantity: 10 },
  { vendorId: TONATON, categoryId: 10, name: "Universal Gear Knob — Leather (Automatic)", description: "Premium leather gear selector knob for automatic vehicles. Universal thread adapter included.", price: "95.00", brand: "Sparco", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "TN-INT-005", quantity: 35 },
  { vendorId: TONATON, categoryId: 10, name: "Toyota Camry Rearview Mirror (Dimming)", description: "Auto-dimming rearview mirror for Camry 2012-2017. Reduces glare at night. OEM clip.", price: "280.00", brand: "Gentex", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2012, yearTo: 2017, sku: "TN-INT-006", oemPartNumber: "87810-06110", quantity: 7 },
  { vendorId: TONATON, categoryId: 10, name: "Hyundai Tucson Airbag Module (Driver)", description: "Used driver airbag module from Tucson 2016 (undeployed). Verified undeployed. Includes clock spring.", price: "680.00", brand: "Hyundai OEM", condition: "used", vehicleMake: "Hyundai", vehicleModel: "Tucson", yearFrom: 2016, yearTo: 2021, sku: "TN-INT-007", quantity: 2 },
  { vendorId: TONATON, categoryId: 10, name: "Honda CR-V Instrument Cluster", description: "Used instrument cluster from CR-V 2013. Speedometer and all gauges working. Miles or km dial.", price: "520.00", brand: "Honda OEM", condition: "used", vehicleMake: "Honda", vehicleModel: "CR-V", yearFrom: 2012, yearTo: 2016, sku: "TN-INT-008", quantity: 2 },
  { vendorId: TONATON, categoryId: 10, name: "Toyota Corolla Glove Box Assembly", description: "Used glove compartment door with latch from Corolla E170 2014-2019. Black. Good condition.", price: "160.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2014, yearTo: 2019, sku: "TN-INT-009", quantity: 4 },
  { vendorId: TONATON, categoryId: 10, name: "Universal Center Console Organizer", description: "Leather-look center console tray with USB and phone slots. Fits most cars with 15–22cm console gap.", price: "120.00", brand: "WeatherTech", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-INT-010", quantity: 40 },
];

const cat10_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 10, name: "Honda Civic Leather Seat Covers", description: "Custom-fit PU leather seat covers for Civic FD/FB. Black, airbag-safe. Front + rear set.", price: "350.00", brand: "Coverking", condition: "new", vehicleMake: "Honda", vehicleModel: "Civic", yearFrom: 2006, yearTo: 2015, sku: "JJ-INT-001", quantity: 10, featured: true },
  { vendorId: JIJI, categoryId: 10, name: "Toyota Hilux Seat (Front Right, Used)", description: "Used right front seat from Hilux 2012 in grey fabric. Good condition, no tears or springs.", price: "380.00", brand: "Toyota OEM", condition: "used", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2011, yearTo: 2015, sku: "JJ-INT-002", quantity: 1 },
  { vendorId: JIJI, categoryId: 10, name: "Hyundai Elantra Rubber Floor Mats", description: "All-weather rubber floor mats for Elantra 2011-2019. 4-piece set. Exact-fit moulded tray design.", price: "140.00", brand: "Husky Liners", condition: "new", vehicleMake: "Hyundai", vehicleModel: "Elantra", yearFrom: 2011, yearTo: 2019, sku: "JJ-INT-003", quantity: 20 },
  { vendorId: JIJI, categoryId: 10, name: "Toyota Camry Clock Spring/Spiral Cable", description: "New clock spring for Camry 2012-2017. Restores horn, cruise control and steering wheel controls.", price: "195.00", brand: "Dorman", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2012, yearTo: 2017, sku: "JJ-INT-004", quantity: 10 },
  { vendorId: JIJI, categoryId: 10, name: "VW Jetta Dashboard Upper Trim (Used)", description: "Used dashboard upper trim panel from Jetta Mk6 2012. Beige interior. No cracks or warping.", price: "220.00", brand: "VW OEM", condition: "used", vehicleMake: "Volkswagen", vehicleModel: "Jetta", yearFrom: 2011, yearTo: 2018, sku: "JJ-INT-005", quantity: 1 },
  { vendorId: JIJI, categoryId: 10, name: "Universal Car Sun Visor Extender", description: "Sun visor extension clip-on for all cars. Blocks low-angle sun. UV protection tinted.", price: "45.00", brand: "Raytek", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "JJ-INT-006", quantity: 80 },
  { vendorId: JIJI, categoryId: 10, name: "Nissan Almera Center Console Lid (Used)", description: "Used center armrest/lid from Almera N16. Correct hinge and latch. Black interior colour.", price: "120.00", brand: "Nissan OEM", condition: "used", vehicleMake: "Nissan", vehicleModel: "Almera", yearFrom: 2000, yearTo: 2006, sku: "JJ-INT-007", quantity: 2 },
  { vendorId: JIJI, categoryId: 10, name: "Toyota Land Cruiser Prado Seat Covers", description: "Premium 3-row seat cover set for Prado 120 & 150. 7-seat version. Leather-look, tan colour.", price: "890.00", brand: "Carhartt", condition: "new", vehicleMake: "Toyota", vehicleModel: "Land Cruiser Prado", yearFrom: 2003, yearTo: 2022, sku: "JJ-INT-008", quantity: 4, featured: true },
  { vendorId: JIJI, categoryId: 10, name: "Honda Accord Gear Shift Assembly (Auto)", description: "Used gear shift assembly from Accord 2012 2.4L automatic. PRND gate complete. Button works.", price: "180.00", brand: "Honda OEM", condition: "used", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2008, yearTo: 2015, sku: "JJ-INT-009", quantity: 2 },
  { vendorId: JIJI, categoryId: 10, name: "Toyota Corolla Front Seat Belt (Right)", description: "New front right seat belt for Corolla 2003-2013. Includes buckle and pre-tensioner. Direct fit.", price: "270.00", brand: "Dorman", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2013, sku: "JJ-INT-010", quantity: 8 },
];

// ─── CAT 11: Audio & Entertainment ───────────────────────────────────────────

const cat11_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 11, name: "10-Inch Android Car Stereo (Universal 2DIN)", description: "10-inch 2DIN Android 12 head unit. GPS, Wi-Fi, Bluetooth, Apple CarPlay/Android Auto. 4+64GB.", price: "1250.00", brand: "Joying", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2018, sku: "TN-AUD-001", quantity: 12, featured: true },
  { vendorId: TONATON, categoryId: 11, name: "Pioneer 6×9 Coaxial Speaker Pair", description: "6×9-inch 3-way coaxial speakers. 350W peak power. Full range audio. Fits rear deck of most sedans.", price: "380.00", brand: "Pioneer", condition: "new", vehicleMake: "Toyota", vehicleModel: "Camry", yearFrom: 2003, yearTo: 2022, sku: "TN-AUD-002", quantity: 20 },
  { vendorId: TONATON, categoryId: 11, name: "12-Inch Subwoofer with Enclosure Box", description: "12-inch 1200W peak subwoofer in ported MDF box. Deep bass for Accra traffic cruising.", price: "680.00", brand: "Rockford Fosgate", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "TN-AUD-003", quantity: 8 },
  { vendorId: TONATON, categoryId: 11, name: "4-Channel Amplifier 1000W", description: "Class AB 4-channel amp. 250W per channel. Built-in crossover. For door speakers or sub.", price: "560.00", brand: "JL Audio", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "TN-AUD-004", quantity: 6 },
  { vendorId: TONATON, categoryId: 11, name: "GPS Navigator (7-Inch, Ghana Maps)", description: "7-inch portable GPS with offline Ghana, West Africa and Pan-Africa maps. Speed camera alerts.", price: "420.00", brand: "Garmin Drive 52", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-AUD-005", quantity: 10 },
  { vendorId: TONATON, categoryId: 11, name: "Reverse Camera with 4.3-Inch Monitor", description: "Waterproof reverse/backup camera kit with 4.3-inch mirror monitor. Night vision, parking lines.", price: "185.00", brand: "Pyle", condition: "new", vehicleMake: "Toyota", vehicleModel: "Hilux", yearFrom: 2005, yearTo: 2022, sku: "TN-AUD-006", quantity: 25 },
  { vendorId: TONATON, categoryId: 11, name: "Dash Cam (Front + Rear, 4K+1080P)", description: "Dual dash cam with 4K front and 1080P rear. Night vision, G-sensor, loop recording, GPS.", price: "580.00", brand: "Vantrue", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-AUD-007", quantity: 10 },
  { vendorId: TONATON, categoryId: 11, name: "Toyota Specific Android Radio — Corolla 2014-19", description: "Toyota-specific 9-inch Android 11 radio for Corolla E170. OEM canbus, steering controls, AC.", price: "1480.00", brand: "Joying", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2014, yearTo: 2019, sku: "TN-AUD-008", quantity: 7 },
  { vendorId: TONATON, categoryId: 11, name: "Bluetooth Car Adapter — 3.5mm Aux + FM", description: "Bluetooth 5.0 car adapter with FM transmitter. Works with any car. Hands-free calls, USB charging.", price: "75.00", brand: "Anker Roav", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "TN-AUD-009", quantity: 50 },
  { vendorId: TONATON, categoryId: 11, name: "USB-C + Type-A Dual Car Charger (45W)", description: "Fast-charge dual USB car charger. 45W USB-C PD for iPhones and Samsung. Always-on port.", price: "85.00", brand: "Anker", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "TN-AUD-010", quantity: 60 },
];

const cat11_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 11, name: "Pioneer DEH-S1250UB CD/USB Car Radio", description: "Pioneer single DIN CD/USB head unit with Bluetooth. Fits any standard DIN slot. Good daily radio.", price: "320.00", brand: "Pioneer", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "JJ-AUD-001", quantity: 15, featured: true },
  { vendorId: JIJI, categoryId: 11, name: "Sony 6.5-Inch Coaxial Speaker Set", description: "Sony 6.5-inch 2-way coaxial speakers. 270W peak. Fits most front door positions.", price: "180.00", brand: "Sony", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "JJ-AUD-002", quantity: 22 },
  { vendorId: JIJI, categoryId: 11, name: "Used JVC Head Unit with Bluetooth", description: "Used JVC KD-X162 digital media receiver. Bluetooth, USB. Good condition from trade-in.", price: "150.00", brand: "JVC", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2020, sku: "JJ-AUD-003", quantity: 3 },
  { vendorId: JIJI, categoryId: 11, name: "10-Inch Subwoofer with Sealed Box", description: "10-inch 800W peak subwoofer in compact sealed box. Budget-friendly bass upgrade for small cars.", price: "380.00", brand: "Kenwood", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-AUD-004", quantity: 10 },
  { vendorId: JIJI, categoryId: 11, name: "Full HD Dash Cam (Front Only)", description: "1080P front-facing dash cam. Loop record, G-sensor. 2.4-inch LCD. Excellent value.", price: "155.00", brand: "Viofo A119", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-AUD-005", quantity: 20 },
  { vendorId: JIJI, categoryId: 11, name: "Android Auto/CarPlay Wireless Dongle", description: "Wireless Apple CarPlay and Android Auto adapter. Plug into any wired CarPlay head unit.", price: "280.00", brand: "Carlinkit", condition: "new", vehicleMake: "Toyota", vehicleModel: "RAV4", yearFrom: 2019, yearTo: 2024, sku: "JJ-AUD-006", quantity: 12 },
  { vendorId: JIJI, categoryId: 11, name: "7-Inch Android Car Stereo (2DIN)", description: "7-inch 2DIN Android 10 radio with GPS, Bluetooth, WiFi. Universal fit. 2+32GB memory.", price: "620.00", brand: "Atoto", condition: "new", vehicleMake: "Honda", vehicleModel: "Accord", yearFrom: 2003, yearTo: 2018, sku: "JJ-AUD-007", quantity: 8 },
  { vendorId: JIJI, categoryId: 11, name: "FM Bluetooth Transmitter — USB-C Charging", description: "FM car transmitter with Bluetooth 5.0. 2 USB ports for charging. Hands-free, Hi-Fi sound.", price: "55.00", brand: "Nulaxy", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2000, yearTo: 2024, sku: "JJ-AUD-008", quantity: 60 },
  { vendorId: JIJI, categoryId: 11, name: "Reverse Camera (Waterproof, Night Vision)", description: "Wide-angle 170° reverse camera. Night vision IR. Universal fitment. Works with any monitor.", price: "85.00", brand: "Pyle", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-AUD-009", quantity: 35 },
  { vendorId: JIJI, categoryId: 11, name: "2-Channel Amplifier 600W", description: "Class AB 2-channel 600W amp. Bridgeable to mono for sub. RCA input. For budget builds.", price: "320.00", brand: "Crunch", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-AUD-010", quantity: 6 },
];

// ─── CAT 12: Safety & Security ────────────────────────────────────────────────

const cat12_tonaton: Product[] = [
  { vendorId: TONATON, categoryId: 12, name: "GPS Vehicle Tracker (Real-Time, SIM)", description: "Real-time GPS tracker with MTN/AirtelTigo SIM support. Live location on Android/iOS app. Geofencing.", price: "350.00", brand: "Queclink", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-SAF-001", quantity: 30, featured: true },
  { vendorId: TONATON, categoryId: 12, name: "Car Alarm System with Remote Start", description: "2-way LCD car alarm. Remote start, shock sensor, siren. Compatible with most cars. Pro installation guide.", price: "580.00", brand: "Viper", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-SAF-002", quantity: 10 },
  { vendorId: TONATON, categoryId: 12, name: "Central Locking Kit (Universal 4-Door)", description: "4-door central locking actuator kit with control module. Adds remote locking to manual-lock cars.", price: "195.00", brand: "Easyguard", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2015, sku: "TN-SAF-003", quantity: 20 },
  { vendorId: TONATON, categoryId: 12, name: "OBD2 Immobilizer with Bluetooth", description: "OBD2-port engine immobilizer. Pairs to your phone via Bluetooth. Engine won't start without app auth.", price: "280.00", brand: "Autowatch", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2008, yearTo: 2024, sku: "TN-SAF-004", quantity: 15 },
  { vendorId: TONATON, categoryId: 12, name: "Parking Sensor Kit (4 Sensors, Rear)", description: "Rear 4-sensor parking kit with buzzer. Reverse trigger auto-on. Easy DIY installation. Multiple colours.", price: "155.00", brand: "Steelmate", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-SAF-005", quantity: 25 },
  { vendorId: TONATON, categoryId: 12, name: "Dual Front+Rear Dash Cam with Parking Mode", description: "2K+1080P dual dash cam with 24hr parking mode. G-sensor, GPS speed logging. 128GB compatible.", price: "650.00", brand: "BlackVue DR750X", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-SAF-006", quantity: 8 },
  { vendorId: TONATON, categoryId: 12, name: "First Aid Kit — 50-Piece Automotive", description: "Ghana Road Transport authority-compliant first aid kit. Bandages, CPR shield, gloves, tourniquet.", price: "95.00", brand: "Surefit", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-SAF-007", quantity: 60 },
  { vendorId: TONATON, categoryId: 12, name: "1kg ABC Fire Extinguisher (Vehicle)", description: "1kg ABC dry powder fire extinguisher with vehicle bracket. GRA compliant. 2-year certification.", price: "120.00", brand: "Firex", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-SAF-008", quantity: 45 },
  { vendorId: TONATON, categoryId: 12, name: "Reflective Warning Triangle (Pair)", description: "DVLA-approved collapsible reflective triangle. 200m visibility. Folds flat into carry case. Pair.", price: "75.00", brand: "Michelin", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-SAF-009", quantity: 80 },
  { vendorId: TONATON, categoryId: 12, name: "Heavy-Duty Wheel Lock/Clamp (Universal)", description: "Yellow heavy-duty wheel clamp. Fits 13-22 inch tires. Anti-theft. 2 keys included.", price: "350.00", brand: "Master Lock", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "TN-SAF-010", quantity: 15 },
];

const cat12_jiji: Product[] = [
  { vendorId: JIJI, categoryId: 12, name: "Budget GPS Tracker (SIM Card Type)", description: "Hidden GPS tracker. Works with any MTN SIM. SMS location. 12V hardwire or battery model.", price: "180.00", brand: "Coban", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-SAF-001", quantity: 25, featured: true },
  { vendorId: JIJI, categoryId: 12, name: "Car Alarm + Central Lock Kit Bundle", description: "2-in-1 alarm and central locking kit. Includes 2 remotes. Anti-hijack feature. Easy to wire.", price: "250.00", brand: "Mongoose", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2022, sku: "JJ-SAF-002", quantity: 12 },
  { vendorId: JIJI, categoryId: 12, name: "4-Sensor Parking Kit (Front or Rear)", description: "4 ultrasonic parking sensors with LED display. Buzzer warning. Plugs into reverse light.", price: "130.00", brand: "Steelmate", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-SAF-003", quantity: 20 },
  { vendorId: JIJI, categoryId: 12, name: "Viper 350 Car Alarm System", description: "Used Viper 350 car alarm with 2 remotes. All sensors and siren tested working. Great for budget install.", price: "150.00", brand: "Viper", condition: "used", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2020, sku: "JJ-SAF-004", quantity: 2 },
  { vendorId: JIJI, categoryId: 12, name: "Wheel Clamp Yellow (Universal 14-22 inch)", description: "Steel wheel clamp with 2 keys. Fits 14-22 inch rims. Good visible deterrent for car theft.", price: "220.00", brand: "BullGuard", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-SAF-005", quantity: 10 },
  { vendorId: JIJI, categoryId: 12, name: "1080P Front Dash Cam (Budget)", description: "Simple 1080P front dash cam with 2.4-inch screen. Loop recording. Great for evidence collection.", price: "120.00", brand: "Apeman", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-SAF-006", quantity: 22 },
  { vendorId: JIJI, categoryId: 12, name: "First Aid Kit (Basic 20-Piece)", description: "Basic travel first aid kit. Bandages, antiseptic, scissors and gloves. Compact pouch. Car must-have.", price: "55.00", brand: "Be Safe", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-SAF-007", quantity: 80 },
  { vendorId: JIJI, categoryId: 12, name: "Reflective Warning Triangle (Single)", description: "Single reflective warning triangle. Folds flat. DVLA recognised. 150m visibility at night.", price: "40.00", brand: "Local Brand", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-SAF-008", quantity: 120 },
  { vendorId: JIJI, categoryId: 12, name: "2kg ABC Fire Extinguisher (Commercial)", description: "2kg dry powder extinguisher. Suitable for cars and minibuses. GRA compliant. Wall or dash bracket.", price: "180.00", brand: "Firex", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-SAF-009", quantity: 30 },
  { vendorId: JIJI, categoryId: 12, name: "Wireless Reverse Camera + 4.3-Inch Monitor", description: "Wireless backup camera kit. No cable routing. 4.3-inch LCD monitor clips to mirror. Night vision.", price: "210.00", brand: "Pyle", condition: "new", vehicleMake: "Toyota", vehicleModel: "Corolla", yearFrom: 2003, yearTo: 2024, sku: "JJ-SAF-010", quantity: 14, featured: true },
];

// ─── COMBINE ALL ──────────────────────────────────────────────────────────────

const ALL_PRODUCTS: Product[] = [
  ...cat1_tonaton,  ...cat1_jiji,
  ...cat2_tonaton,  ...cat2_jiji,
  ...cat3_tonaton,  ...cat3_jiji,
  ...cat4_tonaton,  ...cat4_jiji,
  ...cat5_tonaton,  ...cat5_jiji,
  ...cat6_tonaton,  ...cat6_jiji,
  ...cat7_tonaton,  ...cat7_jiji,
  ...cat8_tonaton,  ...cat8_jiji,
  ...cat9_tonaton,  ...cat9_jiji,
  ...cat10_tonaton, ...cat10_jiji,
  ...cat11_tonaton, ...cat11_jiji,
  ...cat12_tonaton, ...cat12_jiji,
];

// ─── SEED ─────────────────────────────────────────────────────────────────────

async function main() {
  const db = await getDb();
  if (!db) throw new Error("Database connection failed — check SUPABASE_DATABASE_URL");

  console.log(`Seeding ${ALL_PRODUCTS.length} products across 12 categories for 2 vendors...`);

  const BATCH = 20;
  let inserted = 0;

  for (let i = 0; i < ALL_PRODUCTS.length; i += BATCH) {
    const batch = ALL_PRODUCTS.slice(i, i + BATCH).map((p) => ({
      vendorId:     p.vendorId,
      categoryId:   p.categoryId,
      name:         p.name,
      description:  p.description,
      price:        p.price,
      currency:     "GHS" as const,
      brand:        p.brand,
      condition:    p.condition,
      vehicleMake:  p.vehicleMake,
      vehicleModel: p.vehicleModel,
      yearFrom:     p.yearFrom,
      yearTo:       p.yearTo,
      sku:          p.sku,
      quantity:     p.quantity,
      minOrderQty:  1,
      images:       [] as string[],
      status:       "active" as const,
      featured:     p.featured ?? false,
    }));

    await db.insert(products).values(batch);
    inserted += batch.length;
    console.log(`  ✓ ${inserted}/${ALL_PRODUCTS.length} inserted`);
  }

  console.log(`\nDone! ${inserted} products seeded successfully.`);
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
